username: MNTGXO
maxLines: 10
messages:
  issueClosed: Closed issue [#{number}]({url}) in [{repo}]({repoUrl})
  issueOpened: 'Opened issue [#{number}]({url}) in [{repo}]({repoUrl})'
  pr: 'Opened PR [#{number}]({url}) in [{repo}]({repoUrl})'
  prMerged: 'Merged PR [#{number}]({url}) in [{repo}]({repoUrl})'
  prClosed: 'Closed PR [#{number}]({url}) in [{repo}]({repoUrl})'
  starred: '⭐ Starred [{repo}]({repoUrl})'
  commit: '⬆️ Pushed {commitCount} commit(s) to [{repo}]({repoUrl})'
  release: '🚀 Released [{name}]({url}) in [{repo}]({repoUrl})'
  fork: '🍴 Forked [{repo}]({repoUrl})'
  wiki: '📝 Updated wiki in [{repo}]({repoUrl})'
